/**
 * Regenerates src/index.ts from what the source actually exports.
 *
 *   node tools/gen-index.mjs
 *
 * A hand-maintained barrel drifts: a component gets a new prop type, nobody
 * re-exports it, and a consumer trying to type a wrapper has to import from a
 * deep path or redeclare it. Generating the file makes that class of omission
 * impossible.
 *
 * The scan is deliberately a regex over top-level declarations rather than a
 * TypeScript AST pass. It only has to understand the declaration forms the
 * conventions permit, and keeping it dependency-free means it runs anywhere
 * without an install step.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { join, relative } from 'node:path'

// fileURLToPath rather than `.pathname`: on Windows the latter yields
// "/E:/work/..." with a leading slash and percent-encoded spaces, neither of
// which node:path will join correctly.
const SRC = fileURLToPath(new URL('../src/', import.meta.url))

/** node:path emits backslashes on Windows; import specifiers never may. */
const posix = (p) => p.split('\\').join('/')

/** Top-level `export` forms the conventions allow. */
const VALUE = /^export\s+(?:async\s+)?(?:function|const|let|class)\s+([A-Za-z_$][\w$]*)/gm
const TYPE = /^export\s+(?:type|interface)\s+([A-Za-z_$][\w$]*)/gm

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) yield* walk(path)
    else if (/\.tsx?$/.test(entry.name) && !/\.(test|spec)\./.test(entry.name)) yield path
  }
}

function collect(source, pattern) {
  const found = new Set()
  for (const match of source.matchAll(pattern)) found.add(match[1])
  return [...found].sort()
}

const sections = [
  ['Providers', 'providers'],
  ['Hooks', 'hooks'],
  ['Primitives', 'primitives'],
  ['Icons', 'icons'],
  ['Utilities', 'utils'],
  ['Components', 'components'],
]

const files = []
for await (const file of walk(SRC)) files.push(file)
files.sort()

const duplicates = new Map()
let out = `/* ---------------------------------------------------------------------------
 * @tular/ui — public surface
 *
 * GENERATED by tools/gen-index.mjs. Do not edit by hand; re-run the generator.
 *
 * Every module exports its values AND its prop types, so a consumer can type a
 * wrapper without reaching into dist/.
 * ------------------------------------------------------------------------- */

import './styles/index.css';
`

for (const [title, dir] of sections) {
  const inSection = files.filter((f) => posix(relative(SRC, f)).startsWith(dir + '/'))
  if (!inSection.length) continue

  out += `\n/* ------------------------------------------------------------------------ */\n`
  out += `/* ${title} */\n`
  out += `/* ------------------------------------------------------------------------ */\n\n`

  for (const file of inSection) {
    const source = await readFile(file, 'utf8')
    const values = collect(source, VALUE)
    const types = collect(source, TYPE)
    if (!values.length && !types.length) continue

    const specifier = './' + posix(relative(SRC, file)).replace(/\.tsx?$/, '')
    for (const name of [...values, ...types]) {
      duplicates.set(name, (duplicates.get(name) ?? 0) + 1)
    }
    if (values.length) out += `export { ${values.join(', ')} } from '${specifier}';\n`
    if (types.length) out += `export type { ${types.join(', ')} } from '${specifier}';\n`
  }
}

const clashes = [...duplicates].filter(([, n]) => n > 1).map(([name]) => name)
if (clashes.length) {
  console.error(`Duplicate exported names would collide in the barrel: ${clashes.join(', ')}`)
  process.exit(1)
}

await writeFile(join(SRC, 'index.ts'), out)
console.log(`index.ts: ${duplicates.size} exports from ${files.length} modules`)
