/* ---------------------------------------------------------------------------
 * @tular/ui — public surface
 *
 * GENERATED by tools/gen-index.mjs. Do not edit by hand; re-run the generator.
 *
 * Every module exports its values AND its prop types, so a consumer can type a
 * wrapper without reaching into dist/.
 * ------------------------------------------------------------------------- */

import './styles/index.css';

/* ------------------------------------------------------------------------ */
/* Providers */
/* ------------------------------------------------------------------------ */

export { ThemeProvider, themeInitScript, useTheme } from './providers/ThemeProvider';
export type { ResolvedTheme, ThemeContextValue, ThemePreference, ThemeProviderProps } from './providers/ThemeProvider';

/* ------------------------------------------------------------------------ */
/* Hooks */
/* ------------------------------------------------------------------------ */

export { surfaceContains } from './hooks/surfaceContains';
export { useControllableState } from './hooks/useControllableState';
export type { UseControllableStateOptions } from './hooks/useControllableState';
export { useDismiss } from './hooks/useDismiss';
export type { UseDismissOptions } from './hooks/useDismiss';
export { useEventCallback } from './hooks/useEventCallback';
export { FLIP_ARRIVE_AFTER_MS, FLIP_LEAVE_MS, FLIP_MOVE_MS, useFlip } from './hooks/useFlip';
export { getFocusable, useFocusTrap } from './hooks/useFocusTrap';
export type { UseFocusTrapOptions } from './hooks/useFocusTrap';
export { useMediaQuery } from './hooks/useMediaQuery';
export { useReducedMotion } from './hooks/useReducedMotion';
export { REVEAL_MAX_WAIT, REVEAL_STEP, holdReveals, releaseReveals, useRevealOnView } from './hooks/useRevealOnView';
export { useScrollLock } from './hooks/useScrollLock';

/* ------------------------------------------------------------------------ */
/* Primitives */
/* ------------------------------------------------------------------------ */

export { Portal } from './primitives/Portal';
export type { PortalProps } from './primitives/Portal';
export { Slot, Slottable, composeRefs } from './primitives/Slot';
export type { SlotProps, SlottableProps } from './primitives/Slot';
export { VisuallyHidden } from './primitives/VisuallyHidden';
export type { VisuallyHiddenProps } from './primitives/VisuallyHidden';

/* ------------------------------------------------------------------------ */
/* Icons */
/* ------------------------------------------------------------------------ */

export { ICON_NAMES, Icon } from './icons/Icon';
export type { IconName, IconProps } from './icons/Icon';

/* ------------------------------------------------------------------------ */
/* Utilities */
/* ------------------------------------------------------------------------ */

export { cx } from './utils/cx';
export type { ClassValue } from './utils/cx';

/* ------------------------------------------------------------------------ */
/* Components */
/* ------------------------------------------------------------------------ */

export { Avatar, AvatarGroup } from './components/Avatar/Avatar';
export type { AvatarGroupProps, AvatarProps, AvatarShape, AvatarSize } from './components/Avatar/Avatar';
export { getInitials } from './components/Avatar/getInitials';
export { Badge } from './components/Badge/Badge';
export type { BadgeEmphasis, BadgeProps, BadgeSize, BadgeVariant } from './components/Badge/Badge';
export { Banner } from './components/Banner/Banner';
export type { BannerEmphasis, BannerProps, BannerStorage, BannerVariant } from './components/Banner/Banner';
export { Button } from './components/Button/Button';
export type { ButtonProps, ButtonSize, ButtonVariant } from './components/Button/Button';
export { ButtonGroup } from './components/ButtonGroup/ButtonGroup';
export type { ButtonGroupOrientation, ButtonGroupProps } from './components/ButtonGroup/ButtonGroup';
export { Card, CardBody, CardFooter, CardHeader } from './components/Card/Card';
export type { CardPadding, CardProps, CardSectionProps, CardVariant } from './components/Card/Card';
export { cardRoleAllowsAutomaticLabel } from './components/Card/cardA11y';
export { BarChart } from './components/Chart/BarChart';
export type { BarChartProps } from './components/Chart/BarChart';
export { BarList } from './components/Chart/BarList';
export type { BarListItem, BarListProps } from './components/Chart/BarList';
export { DonutChart } from './components/Chart/DonutChart';
export type { DonutChartProps, DonutItem } from './components/Chart/DonutChart';
export { Gauge } from './components/Chart/Gauge';
export type { GaugeProps } from './components/Chart/Gauge';
export { Heatmap } from './components/Chart/Heatmap';
export type { HeatmapProps } from './components/Chart/Heatmap';
export { ChartLegend, LineChart } from './components/Chart/LineChart';
export type { ChartLegendItem, ChartSeries, ChartThreshold, LineChartProps } from './components/Chart/LineChart';
export { Sparkline } from './components/Chart/Sparkline';
export type { SparklineProps } from './components/Chart/Sparkline';
export { chartColor, finiteValues, niceTicks, useChartWidth } from './components/Chart/chartScale';
export { Checkbox } from './components/Checkbox/Checkbox';
export type { CheckboxProps, CheckboxSize } from './components/Checkbox/Checkbox';
export { Code, CodeBlock } from './components/Code/Code';
export type { CodeBlockProps, CodeProps } from './components/Code/Code';
export { CodeInput } from './components/CodeInput/CodeInput';
export type { CodeInputProps, CodeInputSize } from './components/CodeInput/CodeInput';
export { CollapseMark } from './components/CollapseMark/CollapseMark';
export type { CollapseMarkProps } from './components/CollapseMark/CollapseMark';
export { COLLAPSE_MARK_ANGLE, COLLAPSE_MARK_PIECES, COLLAPSE_MARK_PITCH } from './components/CollapseMark/collapseMarkData';
export type { CollapseMarkCellData, CollapseMarkPieceData } from './components/CollapseMark/collapseMarkData';
export { COLLAPSE_MARK_FRAME, COLLAPSE_MARK_SECONDS, collapseBodyAngle, collapseMarkDots, collapseMarkScene, createCollapseMarkPlayer } from './components/CollapseMark/collapseMarkScene';
export type { CollapseMarkBox, CollapseMarkDot, CollapseMarkFrame, CollapseMarkGather, CollapseMarkGatherEvent, CollapseMarkInks, CollapseMarkMessage, CollapseMarkPieceTracks, CollapseMarkPlayer, CollapseMarkScene, CollapseMarkTrack } from './components/CollapseMark/collapseMarkScene';
export { COLLAPSE_MARK_ASSEMBLED, COLLAPSE_MARK_COLLAPSE_START, COLLAPSE_MARK_GATHER_FLIGHT_MS, COLLAPSE_MARK_GATHER_FROM, COLLAPSE_MARK_GATHER_STAGGER_MS, COLLAPSE_MARK_GONE } from './components/CollapseMark/collapseMarkTiming';
export { CompactMark } from './components/CompactMark/CompactMark';
export type { CompactMarkMotion, CompactMarkProps, CompactMarkTone } from './components/CompactMark/CompactMark';
export { compactCutForSize, compactMarkPartition, layoutCompactMark } from './components/CompactMark/compactMarkGeometry';
export type { CompactMarkCell, CompactMarkCorners, CompactMarkCut, CompactMarkEdge, CompactMarkLayout, CompactMarkPiece } from './components/CompactMark/compactMarkGeometry';
export { DIP_ANIMATION, ROUND_KEYFRAMES, ROUND_SPAN, loopStart, useRoundingWindows } from './components/CompactMark/compactMarkRounding';
export { CopyButton, copyTextToClipboard } from './components/CopyButton/CopyButton';
export type { CopyButtonProps, CopyStatus } from './components/CopyButton/CopyButton';
export { DataTable } from './components/DataTable/DataTable';
export type { DataTableColumn, DataTableLabels, DataTableProps, DataTableSort } from './components/DataTable/DataTable';
export { DescriptionDetails, DescriptionList, DescriptionListItem, DescriptionTerm } from './components/DescriptionList/DescriptionList';
export type { DescriptionDetailsProps, DescriptionListItemProps, DescriptionListLayout, DescriptionListProps, DescriptionTermProps } from './components/DescriptionList/DescriptionList';
export { Dialog, DialogBody, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from './components/Dialog/Dialog';
export type { DialogBodyProps, DialogDescriptionProps, DialogFooterProps, DialogHeaderProps, DialogOrigin, DialogProps, DialogSize, DialogTitleProps } from './components/Dialog/Dialog';
export { Drawer, DrawerBody, DrawerDescription, DrawerFooter, DrawerHeader, DrawerTitle } from './components/Drawer/Drawer';
export type { DrawerBodyProps, DrawerDescriptionProps, DrawerFooterProps, DrawerHeaderProps, DrawerProps, DrawerSide, DrawerSize, DrawerTitleProps } from './components/Drawer/Drawer';
export { EmptyState } from './components/EmptyState/EmptyState';
export type { EmptyStateHeadingLevel, EmptyStateProps, EmptyStateSize } from './components/EmptyState/EmptyState';
export { ErrorState } from './components/ErrorState/ErrorState';
export type { ErrorStateHeadingLevel, ErrorStateProps, ErrorStateSize } from './components/ErrorState/ErrorState';
export { Field, useFieldContext, useFieldControl } from './components/Field/Field';
export type { FieldContextValue, FieldControlOverrides, FieldControlProps, FieldProps } from './components/Field/Field';
export { Fieldset } from './components/Fieldset/Fieldset';
export type { FieldsetProps } from './components/Fieldset/Fieldset';
export { FormActions } from './components/FormActions/FormActions';
export type { FormActionsAlign, FormActionsProps, FormActionsStack } from './components/FormActions/FormActions';
export { Grid } from './components/Grid/Grid';
export type { GridProps } from './components/Grid/Grid';
export { IconButton } from './components/IconButton/IconButton';
export type { IconButtonProps, IconButtonShape } from './components/IconButton/IconButton';
export { Inline } from './components/Inline/Inline';
export type { InlineAlign, InlineJustify, InlineProps } from './components/Inline/Inline';
export { InlineMessage } from './components/InlineMessage/InlineMessage';
export type { InlineMessageProps, InlineMessageSize, InlineMessageVariant } from './components/InlineMessage/InlineMessage';
export { Input } from './components/Input/Input';
export type { InputProps, InputSize, InputVariant } from './components/Input/Input';
export { setNativeValue, toText } from './components/Input/inputValue';
export { IRIS_EDGE, IRIS_TRANSITION_MS, iris, irisTransition } from './components/Iris/iris';
export type { IrisOptions, IrisStop, IrisTransitionOptions } from './components/Iris/iris';
export { Kbd } from './components/Kbd/Kbd';
export type { KbdProps, KbdSize } from './components/Kbd/Kbd';
export { isApplePlatform, parseShortcut } from './components/Kbd/shortcut';
export type { ShortcutKey } from './components/Kbd/shortcut';
export { LOADING_STATE_ARRIVAL, LOADING_STATE_DELAY, LOADING_STATE_POP, LOADING_STATE_SECONDS, LOADING_STATE_WINDUP, LoadingState, useLoadsSettled } from './components/LoadingState/LoadingState';
export type { LoadingStateProps } from './components/LoadingState/LoadingState';
export { Markdown, safeMarkdownImage, safeMarkdownLink } from './components/Markdown/Markdown';
export type { MarkdownProps } from './components/Markdown/Markdown';
export { Menu, MenuCheckboxItem, MenuGroup, MenuItem, MenuRadioGroup, MenuRadioItem, MenuSeparator } from './components/Menu/Menu';
export type { MenuCheckboxItemProps, MenuGroupProps, MenuItemProps, MenuProps, MenuRadioGroupProps, MenuRadioItemProps, MenuSeparatorProps } from './components/Menu/Menu';
export { Meter } from './components/Meter/Meter';
export type { MeterProps, MeterSize } from './components/Meter/Meter';
export { meterLevel } from './components/Meter/meterLevel';
export type { MeterLevel, MeterThresholds } from './components/Meter/meterLevel';
export { PageHeader } from './components/PageHeader/PageHeader';
export type { PageHeaderLevel, PageHeaderProps } from './components/PageHeader/PageHeader';
export { Pagination } from './components/Pagination/Pagination';
export type { PaginationProps } from './components/Pagination/Pagination';
export { paginationRange } from './components/Pagination/paginationRange';
export type { PaginationItem } from './components/Pagination/paginationRange';
export { Panel } from './components/Panel/Panel';
export type { PanelLevel, PanelPadding, PanelProps, PanelVariant } from './components/Panel/Panel';
export { Popover } from './components/Popover/Popover';
export type { PopoverProps } from './components/Popover/Popover';
export { Progress } from './components/Progress/Progress';
export type { ProgressProps, ProgressSize, ProgressVariant } from './components/Progress/Progress';
export { Radio, RadioGroup } from './components/Radio/Radio';
export type { RadioGroupOrientation, RadioGroupProps, RadioProps, RadioSize, RadioVariant } from './components/Radio/Radio';
export { ScrollArea } from './components/ScrollArea/ScrollArea';
export type { ScrollAreaEdges, ScrollAreaProps } from './components/ScrollArea/ScrollArea';
export { SearchInput } from './components/SearchInput/SearchInput';
export type { SearchInputProps } from './components/SearchInput/SearchInput';
export { SearchSelect } from './components/SearchSelect/SearchSelect';
export type { SearchSelectOption, SearchSelectProps } from './components/SearchSelect/SearchSelect';
export { SegmentedControl } from './components/SegmentedControl/SegmentedControl';
export type { SegmentedControlItem, SegmentedControlProps, SegmentedControlSize } from './components/SegmentedControl/SegmentedControl';
export { Select, SelectGroup, SelectOption } from './components/Select/Select';
export type { SelectGroupProps, SelectOptionProps, SelectProps, SelectSize } from './components/Select/Select';
export { Separator } from './components/Separator/Separator';
export type { SeparatorOrientation, SeparatorProps } from './components/Separator/Separator';
export { Skeleton } from './components/Skeleton/Skeleton';
export type { SkeletonProps, SkeletonVariant } from './components/Skeleton/Skeleton';
export { Spinner } from './components/Spinner/Spinner';
export type { SpinnerProps, SpinnerSize } from './components/Spinner/Spinner';
export { Stack } from './components/Stack/Stack';
export type { SpaceScale, StackAlign, StackJustify, StackProps } from './components/Stack/Stack';
export { Steps } from './components/Steps/Steps';
export type { StepItem, StepStatus, StepsOrientation, StepsProps, StepsSize } from './components/Steps/Steps';
export { Switch } from './components/Switch/Switch';
export type { SwitchProps, SwitchSize } from './components/Switch/Switch';
export { Table, TableBody, TableCell, TableEmpty, TableHead, TableHeaderCell, TableRow } from './components/Table/Table';
export type { TableAlign, TableBodyProps, TableCellProps, TableDensity, TableEmptyProps, TableHeadProps, TableHeaderCellProps, TableProps, TableRowProps, TableSortDirection } from './components/Table/Table';
export { Tab, TabList, TabPanel, Tabs } from './components/Tabs/Tabs';
export type { TabListProps, TabPanelProps, TabProps, TabsActivation, TabsOrientation, TabsProps, TabsSize, TabsVariant } from './components/Tabs/Tabs';
export { Tag } from './components/Tag/Tag';
export type { TagProps, TagSize, TagVariant } from './components/Tag/Tag';
export { Textarea } from './components/Textarea/Textarea';
export type { TextareaProps, TextareaResize, TextareaSize, TextareaVariant } from './components/Textarea/Textarea';
export { ToastProvider, useToast } from './components/Toast/Toast';
export type { ToastAction, ToastContextValue, ToastOptions, ToastPlacement, ToastProviderProps, ToastRecord, ToastVariant } from './components/Toast/Toast';
export { Toolbar, ToolbarGroup, ToolbarSeparator } from './components/Toolbar/Toolbar';
export type { ToolbarGroupProps, ToolbarOrientation, ToolbarProps, ToolbarSeparatorProps } from './components/Toolbar/Toolbar';
export { Tooltip } from './components/Tooltip/Tooltip';
export type { TooltipProps } from './components/Tooltip/Tooltip';
export { computePosition } from './components/_shared/position';
export type { Align, Placement, PositionOptions, PositionResult, Rect, Side, Size } from './components/_shared/position';
export { OverlaySurfaceContext, useOverlaySurface, useOverlaySurfaceValue, useSurfaceLabelId } from './components/_shared/surfaceContext';
export type { OverlaySurface, UseOverlaySurfaceValueOptions } from './components/_shared/surfaceContext';
export { useAnchoredPosition } from './components/_shared/useAnchoredPosition';
export type { UseAnchoredPositionOptions } from './components/_shared/useAnchoredPosition';
export { useAttachedNode } from './components/_shared/useAttachedNode';
export type { AttachedNode } from './components/_shared/useAttachedNode';
export { useModalSurface } from './components/_shared/useModalSurface';
export type { UseModalSurfaceOptions } from './components/_shared/useModalSurface';
export { LOOP_ANIMATION_PREFIX, usePresence } from './components/_shared/usePresence';
export type { Presence, PresenceStatus } from './components/_shared/usePresence';
export { useScrollableRegion } from './components/_shared/useScrollableRegion';
